name: Auto Merge PR on dbt Cloud Success

on:
  check_run:
    types: [completed]

jobs:
  auto-merge:
    if: >
      github.event.check_run.name == 'dbt Cloud' &&
      github.event.check_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/setup-gha-git-cli@v1

      - name: Merge pull request
        run: gh pr merge ${{ github.event.check_run.pull_requests[0].number }} --auto --merge-method merge
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE }}
